version: '3.1'

services:
  mysql:
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
